# Generated by Django 5.1.4 on 2025-01-05 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Book Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author Name')),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Biography', 'Biography')], max_length=50)),
                ('publication_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Year of Publication')),
                ('available_copies', models.PositiveIntegerField(default=0, verbose_name='Available Copies')),
                ('isbn_number', models.CharField(max_length=13, unique=True, verbose_name='ISBN Number')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Book Rating')),
            ],
        ),
    ]
