# Generated by Django 5.1.4 on 2025-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookID',
            field=models.UUIDField(auto_created=True),
        ),
    ]
