# Generated by Django 5.1.4 on 2025-01-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='BookID',
        ),
    ]
