# Generated by Django 5.1.4 on 2025-01-07 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 21, 45, 27, 226362)),
        ),
    ]
