# Generated by Django 5.1.4 on 2025-01-07 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_member_mail_alter_member_membership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 22, 15, 26, 644259)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
