# Generated by Django 5.1.4 on 2025-01-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_member_membership_start_date_alter_staff_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 22, 18, 22, 365409)),
        ),
    ]
